### ISSUE TITLE
Question for set_timeout

### ISSUE THREAD

**Issue by ghost** [eindiran/smbus3#21]
Hello

For SMBus protocol, it seems that the clock stretching max time is 35 ms to avoid anyone take the bus for too long time?
So if we set the timeout value bigger than the value, is it OK?

**Comment by eindiran** [comment]
The answer unfortunately is that it depends. Under the hood, this library is making an `ioctl` syscall. The actual device the user is running will have a driver in the Linux kernel, which may or may not honor the command `I2C_TIMEOUT` from `ioctl`. You will have to try with your device and see whether you can change the timeout. Note that the timeout is in units of 10ms.
